POST https://nodejs-mykh.onrender.com/videos
Content-type: application/json

{
  "title" : "Video 01",
  "description": "This is the first video input",
  "duration" :180
}

###

GET https://nodejs-mykh.onrender.com/videos?search=

###

PUT https://nodejs-mykh.onrender.com/videos/24ec16a5-cb82-4185-ad3c-3c3ed8e6943e
Content-type: application/json

{
  "title" : "Video 004",
  "description": "Esse e o video alterado",
  "duration" :180
}

###

DELETE https://nodejs-mykh.onrender.com/videos/6983be42-e56f-4406-b6a9-a6bb2f584baf


 